### PR TITLE
Post endpoints

### LINKED ISSUE #32: [FEATURE-REQUEST] Endpoint for posts
**Please Describe The Problem To Be Solved**

Please have a look at the spec-sheet for description on what all ednpoints to be created.

**Suggest A Solution or Implementation**

**Screenshots**

### PR DESCRIPTION
**Pull request by grapheo12**
# Changes proposed through this PR
 Adding the proposed endpoints for /article.

**Before submitting this PR, make sure:**

- [x] There is an issue corresponding the changes in this PR.
- [x] The base branch for this PR is master and not based on another PR.
- [x] The changes made are independent from the changes made in other PR's.
- [ ] You have documented the changes made and updated the README file.
- [x] Merging this PR doesn't disrupt functionality or cause a feature to behave unexpectedly.
- [x] PR is ready to be merged, otherwise you've added WIP in the title.

# Information for Review

Please ignore changes in `config.py`, `imgLinks.py`, `posts.py`, `tags.py`. They came as I created this new branch from master.
All work is done in `article_controller.py` and `dto.py`.

---
Concerns #32

### CODE REVIEW

**Comment by thealphadollar** [comment]
@grapheo12 Please resolve the conflicts and update the PR.

**Comment by grapheo12** [comment]
@thealphadollar Can you please reiterate what you told that day regarding using namespace alone instead of blueprints? I forgot the note you made.

**Comment by thealphadollar** [comment]
Instead of using blueprint, you can directly use namespace. I've a
repository named "TriNetra-Clone" where I've used this method.

**Comment by grapheo12** [comment]
Closes #32

**Pull request merged**
